### PR TITLE
upgrade binary

### PR DESCRIPTION
**Pull request by samuelcolvin**
to use wkhtmltox_0.12.5-1.bionic_amd64

### CODE REVIEW

**Comment by dbinetti** [comment]
FYI this fixes #10 but does introduce a new problem: external resources (such as `img` tags or stylesheet links) do not load on Heroku.  The PDF renders, but without any styling, images, external fonts, etc.

**Comment by samuelcolvin** [comment]
@tomhamiltonstubber please can you try this.

**Comment by dbinetti** [comment]
Yes heroku 18

**Comment by dbinetti** [comment]
If there's something else I can to do to help please let me know.  I've verified that downgrading to Heroku-16 solves the problem.

**Comment by samuelcolvin** [comment]
Wait,

> I've verified that downgrading to Heroku-16 solves the problem.

Do you mean this PR works on heroku-16 or the released version of pydf works on heroku-16?

I know the released version of pydf works on heroku-16, this upgrade was supposed to allow us to upgrade to heroku-18.

> external resources (such as img tags or stylesheet links) do not load on Heroku. The PDF renders, but without any styling, images, external fonts, etc.

Are you sure this is unique to heroku? I don't see how it can be specific to heroku, unless there's some library used for that sort of thing that isn't install in the heroku-18 slug.

**Comment by dbinetti** [comment]
I'm talking solely about the PR.

And yes, I know it's odd, but I can use this PR in my local environment with no problem.  And I can use this PR on Heroku-16 with no problem.  But when I no change other than upgrading the stack to Heroku-18 I experience the issue.  

Perhaps I should create a test app to demonstrate?  Would that be helpful?

**Comment by samuelcolvin** [comment]
> Would that be helpful?

I don't think that would help. I've tried building a pdf in the `heroku/heroku:18.v6` docker image and it's working fine.

@tomhamiltonstubber try running it on tutorcruncher with pydf version

    git+git://github.com/tutorcruncher/pydf.git@upgrade-binary#egg=python-pdf

And see how we get on.

**Comment by dbinetti** [comment]
Just tried this again FWIW, and still failing on Heroku-18. Specifically, the static resources are not loading/rendering.  So, for instance, I am using Bootstrap 4 and it is rendering a PDF but doing so as if none of the CSS or JS is loading.  Perhaps that is helpful?  Again, confirming that nothing other than a downgrade to H-16 solves this issue.

**Comment by dbinetti** [comment]
OK, some progress:  I was able to identify that the problem lies in accessing https:// resources v. http:.  I don't know everything they are talking about, but @samuelcolvin might make sense of the thread here:
https://github.com/rposborne/wkhtmltopdf-heroku/issues/41

**Comment by samuelcolvin** [comment]
Humm, I've just tried this on on heroku-18 and it seems to be working fine for me.

**Comment by samuelcolvin** [comment]
all the CSS as well as images are accessed over HTTPS.

**Comment by samuelcolvin** [comment]
@dbinetti if you're still having problems with this then a demo app might be helpful to see how our setups are different.

**Comment by dbinetti** [comment]
OK, it's working now on Heroku-18.  Thanks @samuelcolvin!

I should mention that part of the problem may have been that Heroku wasn't blowing out the old version of `pydf` despite my repeated `purge_cache` commands; I had to completely switch runtimes to make sure things were being installed correctly.  So that might have been the issue the whole time.  Major facepalm.

**Comment by samuelcolvin** [comment]
yup, the only way to get heroku to completely re install is to change the runtime, in this case you can switch between `3.7.2` and `3.7.3` with virtually no other effect.

the problem will be solved when I release a proper version of python-pdf with a new version number.

**Pull request merged**
